"""
Email Agent — formats ranked jobs as an HTML email and sends via Gmail SMTP.
"""

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from langsmith import traceable
from rich.console import Console

console = Console()


def _score_color(score: int) -> str:
    if score >= 80:
        return "#22c55e"  # green
    if score >= 60:
        return "#f59e0b"  # amber
    return "#6b7280"      # grey


def _build_html(state: dict) -> str:
    ranked_jobs  = state.get("ranked_jobs", [])
    raw_profile  = state.get("raw_profile", {})
    preferences  = state.get("preferences", {})
    now          = datetime.now().strftime("%d %b %Y")

    rows = ""
    for job in ranked_jobs:
        score = job.get("match_score", 0)
        color = _score_color(int(score) if str(score).isdigit() else 0)
        url   = job.get("url", "")
        apply = f'<a href="{url}" style="color:#6366f1;">Apply →</a>' if url else "—"
        rows += f"""
        <tr>
          <td style="padding:10px 8px;border-bottom:1px solid #f1f5f9;font-weight:600;color:#1e293b;">
            {job.get('rank','')}.&nbsp;{job.get('title','')}
          </td>
          <td style="padding:10px 8px;border-bottom:1px solid #f1f5f9;color:#475569;">{job.get('company','')}</td>
          <td style="padding:10px 8px;border-bottom:1px solid #f1f5f9;color:#475569;">{job.get('location','')}</td>
          <td style="padding:10px 8px;border-bottom:1px solid #f1f5f9;">
            <span style="background:{color};color:#fff;padding:2px 8px;border-radius:12px;font-size:12px;font-weight:600;">
              {score}/100
            </span>
          </td>
          <td style="padding:10px 8px;border-bottom:1px solid #f1f5f9;color:#64748b;font-size:13px;">
            {job.get('source','')}
          </td>
          <td style="padding:10px 8px;border-bottom:1px solid #f1f5f9;">{apply}</td>
        </tr>
        <tr>
          <td colspan="6" style="padding:4px 8px 12px 8px;border-bottom:1px solid #e2e8f0;
              color:#64748b;font-size:13px;font-style:italic;">
            {job.get('match_reason','')}
          </td>
        </tr>"""

    skills_str = ", ".join(preferences.get("skills", [])[:8])
    titles_str = ", ".join(preferences.get("preferred_titles", []))

    return f"""<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:800px;margin:32px auto;background:#fff;border-radius:12px;
       box-shadow:0 1px 3px rgba(0,0,0,.1);overflow:hidden;">

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:28px 32px;">
      <h1 style="margin:0;color:#fff;font-size:22px;">🤖 Daily Job Hunt Report</h1>
      <p style="margin:6px 0 0;color:#e0e7ff;font-size:14px;">{now} &nbsp;·&nbsp; {len(ranked_jobs)} recommendations for {raw_profile.get('name','you')}</p>
    </div>

    <!-- Profile summary -->
    <div style="padding:20px 32px;background:#f8fafc;border-bottom:1px solid #e2e8f0;">
      <p style="margin:0;color:#475569;font-size:14px;">
        <strong>Searching for:</strong> {titles_str}<br>
        <strong>Key skills:</strong> {skills_str}<br>
        <strong>Location:</strong> {preferences.get('preferred_location','')}
      </p>
    </div>

    <!-- Jobs table -->
    <div style="padding:24px 32px;">
      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <thead>
          <tr style="background:#f1f5f9;">
            <th style="padding:10px 8px;text-align:left;color:#475569;font-size:12px;text-transform:uppercase;">Role</th>
            <th style="padding:10px 8px;text-align:left;color:#475569;font-size:12px;text-transform:uppercase;">Company</th>
            <th style="padding:10px 8px;text-align:left;color:#475569;font-size:12px;text-transform:uppercase;">Location</th>
            <th style="padding:10px 8px;text-align:left;color:#475569;font-size:12px;text-transform:uppercase;">Match</th>
            <th style="padding:10px 8px;text-align:left;color:#475569;font-size:12px;text-transform:uppercase;">Source</th>
            <th style="padding:10px 8px;text-align:left;color:#475569;font-size:12px;text-transform:uppercase;">Link</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
    </div>

    <!-- Footer -->
    <div style="padding:16px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;text-align:center;">
      <p style="margin:0;color:#94a3b8;font-size:12px;">
        Generated by Agentic Job Hunter &nbsp;·&nbsp; Powered by Gemini + LangGraph
      </p>
    </div>
  </div>
</body>
</html>"""


@traceable(name="Email Agent")
async def run_email_agent(state: dict) -> dict:
    console.print("\n[bold green]📧 Email Agent[/bold green] Sending job report by email...")

    email_from     = os.environ.get("EMAIL_FROM", "")
    email_password = os.environ.get("EMAIL_PASSWORD", "")
    email_to       = os.environ.get("EMAIL_TO", "sanchit_gupta2015@pgp.isb.edu")

    if not email_from or not email_password:
        console.print("   [yellow]⚠ EMAIL_FROM / EMAIL_PASSWORD not set — skipping email[/yellow]")
        return {}

    ranked_jobs = state.get("ranked_jobs", [])
    name        = state.get("raw_profile", {}).get("name", "there")
    now         = datetime.now().strftime("%d %b %Y")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🤖 Your Daily Job Report — {len(ranked_jobs)} picks — {now}"
    msg["From"]    = email_from
    msg["To"]      = email_to

    # Plain text fallback
    plain = f"Hi {name},\n\nHere are your top {len(ranked_jobs)} job recommendations for {now}:\n\n"
    for job in ranked_jobs:
        plain += (
            f"{job.get('rank')}. {job.get('title')} @ {job.get('company')}\n"
            f"   Location: {job.get('location')} | Score: {job.get('match_score')}/100\n"
            f"   Why: {job.get('match_reason','')}\n"
            f"   Apply: {job.get('url','N/A')}\n\n"
        )
    plain += "\n-- Agentic Job Hunter"

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(_build_html(state), "html"))

    try:
        with smtplib.SMTP("smtp.mail.yahoo.com", 587) as server:
            server.starttls()
            server.login(email_from, email_password)
            server.sendmail(email_from, email_to, msg.as_string())
        console.print(f"   [dim]→ Email sent to {email_to}[/dim]")
    except Exception as e:
        console.print(f"   [red]⚠ Email failed: {e}[/red]")

    return {}
